services:
  - name: nestjs-backend
    type: web
    runtime: node
    repo: https://github.com/niy42/craftboard.git
    branch: main
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: craftboard_db  
          property: DATABASE_URL
      - key: JWT_SECRET
        value: "e4c2a6b8d0f34860b2e2a5c7f9a3b2d6f8c4e1a2b3c5d7e6f9a1b2c3d4e5f6g7" 

databases:
  - name: craftboard_db  
    region: oregon
    plan: free
