services:
  - name: nestjs-backend
    type: web
    runtime: node
    repo: https://github.com/niy42/craftboard.git
    branch: main
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          name: craftboard_db  
          type: dpg
      - key: JWT_SECRET
        value: ""
        sync: false

databases:
  - name: craftboard_db  
    region: oregon
    plan: free
